version: "3.1"

services:

  nginx:
    image: nginx:alpine
    env_file:
      - .env
    container_name: nginx
    working_dir: /app
    volumes:
        - .:/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "${HTTP_PORT}:80"
    depends_on:
      - php
      - postgres

  php:
    env_file:
      - .env
    build: ./docker/php-fpm
    container_name: php
    environment:
      - XDEBUG_MODE=coverage
    expose:
      - "${PHPFPM_PORT}"
    volumes:
      - .:/app:rw
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - postgres

  postgres:
    image: postgres:11.1-alpine
    env_file:
      - .env
    container_name: postgres
    working_dir: /app
    volumes:
      - ./docker/database:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
